name: Matrix

on:
  push:
    branches:
      - main

jobs:
  build:
   continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

